Repository pq-code-package/mlkem-native, pull requests merged in 2024-10, with the labels that each got.

#168 Prove poly decompress
  cbmc/default.nix
  cbmc/proofs/poly_decompress/Makefile
  cbmc/proofs/poly_decompress/poly_decompress_harness.c
  mlkem/poly.c
  mlkem/poly.h
Labels: ci

#172 tests: Fix bug in export of benchmarking results
  scripts/tests
Labels: bug

#165 Inline scalar [de]compression functions
  cbmc/proofs/poly_compress/Makefile
  mlkem/poly.c
  mlkem/poly.h
Labels: benchmark, ci

#178 Fix CI workflow trigger
  .github/workflows/ci.yml
Labels: ci

#179 Add scalar/Neon/Neon hybrid for Keccak-x4
  .github/workflows/bench.yml
  fips202/asm/aarch64/keccak_f1600_x1_scalar_asm_opt.S
  fips202/asm/aarch64/keccak_f1600_x1_v84a_asm_clean.S
  fips202/asm/aarch64/keccak_f1600_x2_v84a_asm_clean.S
  fips202/asm/aarch64/keccak_f1600_x2_v8a_v84a_asm_hybrid.S
  fips202/asm/aarch64/keccak_f1600_x4_scalar_v84a_asm_hybrid_opt.S
  fips202/asm/aarch64/keccak_f1600_x4_v8a_scalar_hybrid_asm_opt.S
  fips202/asm/aarch64/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
  fips202/asm/asm.h
  fips202/asm/profiles/cortex_a55.h
  fips202/asm/profiles/default.h
  fips202/keccakf1600.c
  mlkem/asm/asm.h
  test/bench_components_kyber.c
Labels: benchmark

#185 Fix gen_matrix()
  mlkem/indcpa.c
Labels: bug

#189 Add Graviton4 benchmarks to CI
  .github/workflows/bench.yml
Labels: benchmark

#196 Add some x86_64 based benchmarks to CI
  .github/workflows/bench.yml
Labels: benchmark

#192 Start adding AVX2 native backend
  .github/actions/functest/action.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  mk/schemes.mk
  mlkem/native/aarch64/arith_native_aarch64.h
  mlkem/native/aarch64/profiles/clean.h
  mlkem/native/aarch64/profiles/opt.h
  mlkem/native/arith_native.h
  mlkem/native/x86_64/README.md
  mlkem/native/x86_64/align.h
  mlkem/native/x86_64/arith_native_x86_64.h
  mlkem/native/x86_64/consts.c
  mlkem/native/x86_64/consts.h
  mlkem/native/x86_64/profiles/default.h
  mlkem/native/x86_64/rej_uniform_avx2.c
  mlkem/rej_uniform.c
  mlkem/sys/config.h
  mlkem/sys/cpucap.h
Labels: benchmark

#204 Simplify C<->Native interface for mulcache computation
  mlkem/native/aarch64/consts.c
  mlkem/native/aarch64/consts.h
  mlkem/native/aarch64/profiles/clean.h
  mlkem/native/aarch64/profiles/opt.h
  mlkem/native/arith_native.h
  mlkem/poly.c
Labels: benchmark

#203 Add AVX2 [inv]NTT from official Kyber repository
  mk/schemes.mk
  mlkem/common.h
  mlkem/indcpa.c
  mlkem/kem.c
  mlkem/native/x86_64/arith_native_x86_64.h
  mlkem/native/x86_64/consts.h
  mlkem/native/x86_64/fq.inc
  mlkem/native/x86_64/intt.S
  mlkem/native/x86_64/ntt.S
  mlkem/native/x86_64/profiles/default.h
  mlkem/native/x86_64/rej_uniform_avx2.c
  mlkem/native/x86_64/shuffle.S
  mlkem/native/x86_64/shuffle.inc
  mlkem/poly.c
  mlkem/poly.h
  mlkem/polyvec.h
  test/bench_components_kyber.c
  test/gen_KAT.c
  test/gen_NISTKAT.c
Labels: benchmark

#209 Add missing use of precomputed mulcache
  mlkem/indcpa.c
  mlkem/ntt.c
  mlkem/ntt.h
  mlkem/poly.c
  mlkem/poly.h
  mlkem/polyvec.c
Labels: benchmark

#207 Cross compilation and Emulation for x86_64 on aarch64 machines
  .astylerc
  .github/actions/bench/action.yml
  .github/actions/cbmc/action.yml
  .github/actions/functest/action.yml
  .github/actions/lint/action.yml
  .github/actions/multi-functest/action.yml
  .github/actions/setup-nix/action.yml
  .github/actions/setup-shell/action.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_any.yml
  .github/workflows/ci_ec2_reusable.yml
  flake.nix
  mk/auto.mk
  mk/bench.mk
  mk/bench_components.mk
  mk/config.mk
  mlkem/sys/cpucap.h
  scripts/tests
Labels: benchmark

#208 Document bounds and remove redundant reductions
  .github/workflows/ci.yml
  mk/schemes.mk
  mlkem/debug/debug.c
  mlkem/debug/debug.h
  mlkem/indcpa.c
  mlkem/native/aarch64/intt_123_45_67_twiddles.S
  mlkem/native/aarch64/intt_clean.S
  mlkem/native/aarch64/intt_opt.S
  mlkem/native/aarch64/ntt_clean.S
  mlkem/native/aarch64/ntt_opt.S
  mlkem/native/aarch64/polyvec_clean.S
  mlkem/native/aarch64/polyvec_opt.S
  mlkem/native/aarch64/profiles/clean.h
  mlkem/native/aarch64/profiles/opt.h
  mlkem/native/x86_64/profiles/default.h
  mlkem/ntt.c
  mlkem/ntt.h
  mlkem/poly.c
  mlkem/polyvec.c
  mlkem/reduce.c
  mlkem/reduce.h
  test/test_bounds.py
Labels: benchmark

#215 Modify semantics of `poly_reduce()` to require unsigned canonical output
  mlkem/debug/debug.c
  mlkem/debug/debug.h
  mlkem/indcpa.c
  mlkem/native/aarch64/poly_clean.S
  mlkem/native/aarch64/poly_opt.S
  mlkem/native/x86_64/arith_native_x86_64.h
  mlkem/native/x86_64/fq.S
  mlkem/native/x86_64/profiles/default.h
  mlkem/poly.c
  mlkem/poly.h
Labels: benchmark

#216 Add AVX2 assembly for base multiplication
  mlkem/native/x86_64/arith_native_x86_64.h
  mlkem/native/x86_64/basemul.S
  mlkem/native/x86_64/basemul.c
  mlkem/native/x86_64/profiles/default.h
  mlkem/native/x86_64/shuffle.S
  scripts/tests
Labels: benchmark, ci

#219 AVX2: Switch to custom NTT coefficient ordering
  mlkem/native/x86_64/basemul.c
  mlkem/native/x86_64/profiles/default.h
  mlkem/native/x86_64/shuffle.S
Labels: benchmark

#220 Add AVX2 Keccak-x4 from XKCP
  fips202/keccakf1600.h
  fips202/native/fips202_native.h
  fips202/native/x86_64/fips202_native_x86_64.h
  fips202/native/x86_64/profiles/xkcp.h
  fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c
  fips202/native/x86_64/xkcp/KeccakP-1600-times4-SnP.h
  fips202/native/x86_64/xkcp/KeccakP-1600-unrolling.macros
  fips202/native/x86_64/xkcp/KeccakP-SIMD256-config.h
  fips202/native/x86_64/xkcp/KeccakP-align.h
  fips202/native/x86_64/xkcp/KeccakP-brg_endian.h
  mk/crypto.mk
Labels: benchmark

#218 Fix tests and GH cache issue
  .github/actions/bench/action.yml
  .github/actions/cbmc/action.yml
  .github/actions/functest/action.yml
  .github/actions/lint/action.yml
  .github/actions/multi-functest/action.yml
  .github/actions/setup-nix/action.yml
  .github/actions/setup-shell/action.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci_ec2_any.yml
  .github/workflows/ci_ec2_reusable.yml
  cbmc/default.nix
  flake.nix
  scripts/tests
Labels: benchmark

#221 Smaller performance improvements of AVX2 backend
  mlkem/native/x86_64/arith_native_x86_64.h
  mlkem/native/x86_64/basemul.c
  mlkem/native/x86_64/fq.S
  mlkem/native/x86_64/profiles/default.h
  scripts/tests
  test/bench_kyber.c
Labels: benchmark

#231 Split nix shells to avoid `no more space left on disk` issue for benchmarking on some resource-limited machines
  .github/actions/bench/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_reusable.yml
  flake.nix
Labels: benchmark

#225 Set C standard to C99
  mk/config.mk
  mlkem/debug/debug.h
  randombytes/randombytes.c
  test/hal/hal.c
Labels: benchmark, ci, alpha

#236 Remove explicit zipping/unzipping of Keccak-x4 state in AVX2 FIPS202 backend
  fips202/native/x86_64/profiles/xkcp.h
  fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c
Labels: benchmark

#229 Fix CI Pull_Request labeled event trigger
  .github/workflows/ci.yml
Labels: benchmark

#237 Add 'out of the box' make to CI
  .github/workflows/ci.yml
  Makefile
Labels: ci

#241 Allow makefile to be compatible with make 3.8
  mk/rules.mk
Labels: benchmark

#245 Allow overwriting default values CC, CPP, AR, LD
  .github/actions/functest/action.yml
  flake.nix
  mk/config.mk
  mk/rules.mk
Labels: benchmark

#232 CBMC proofs for type-safety of reduce.c
  cbmc/proofs/barrett_reduce/Makefile
  cbmc/proofs/barrett_reduce/barrett_reduce_harness.c
  cbmc/proofs/barrett_reduce/cbmc-proof.txt
  cbmc/proofs/fqmul/Makefile
  cbmc/proofs/fqmul/cbmc-proof.txt
  cbmc/proofs/fqmul/fqmul_harness.c
  cbmc/proofs/montgomery_reduce/Makefile
  cbmc/proofs/montgomery_reduce/cbmc-proof.txt
  cbmc/proofs/montgomery_reduce/montgomery_reduce_harness.c
  mlkem/reduce.c
  mlkem/reduce.h
Labels: benchmark

#235 Add proof artefacts for poly_tobytes()
  cbmc/proofs/poly_tobytes/Makefile
  cbmc/proofs/poly_tobytes/cbmc-proof.txt
  mlkem/poly.c
  mlkem/poly.h
Labels: ci

#249 Modify benchmark actions and workflows to allow custom compiler
  .github/actions/bench/action.yml
  .github/actions/setup-shell/action.yml
  .github/actions/setup-ubuntu/action.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  mk/config.mk
Labels: benchmark

#205 Update README to reflect wider scope of repository
  README.md
Labels: ci

#233 Nix cache enhancement in CI and ping clang-tools version to `17.0.6`
  .github/actions/bench/action.yml
  .github/actions/cbmc/action.yml
  .github/actions/functest/action.yml
  .github/actions/lint/action.yml
  .github/actions/multi-functest/action.yml
  .github/actions/setup-nix/action.yml
  .github/actions/setup-shell/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_reusable.yml
  flake.lock
  flake.nix
Labels: benchmark

#258 Prevent clang-format from formatting CBMC contracts on functions
  mlkem/poly.h
  mlkem/reduce.h
Labels: benchmark

#270 AArch64: Simplify polyvec_basemul_acc_montgomery interface
  mlkem/native/aarch64/arith_native_aarch64.h
  mlkem/native/aarch64/polyvec_clean.S
  mlkem/native/aarch64/polyvec_opt.S
  mlkem/native/aarch64/profiles/clean.h
  mlkem/native/aarch64/profiles/opt.h
  test/bench_components_mlkem.c
Labels: benchmark

#269 Remove unused XKCP symbols
  fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c
  fips202/native/x86_64/xkcp/KeccakP-1600-times4-SnP.h
  fips202/native/x86_64/xkcp/KeccakP-1600-unrolling.macros
Labels: benchmark

#273 CI: Set top-level workflow permissions to contents: read
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_any.yml
  .github/workflows/ci_ec2_reusable.yml
Labels: benchmark

#271 Pin CI workflow dependencies
  .github/actions/cbmc/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_reusable.yml
Labels: benchmark

#277 Fix quoting of CFLAGS when fwding from `tests all` to `tests func/kat/nistkat`
  scripts/tests
Labels: benchmark

#279 Add address + UB sanitizer to CI debug tests
  .github/workflows/ci.yml
Labels: benchmark

#285 Fix makefile cflags propagation and duplication issue, remove RNG .a files
  Makefile
  mk/config.mk
  mk/crypto.mk
  mk/nistkat.mk
  mk/schemes.mk
  mlkem/randombytes.h
  test/gen_NISTKAT.c
  test/nistrng/nistrng.h
  test/nistrng/rng.c
Labels: benchmark

#289 Add verbal specification and runtime-checking for `fqmul()`
  mlkem/debug/debug.c
  mlkem/debug/debug.h
  mlkem/ntt.c
  mlkem/poly.c
  mlkem/reduce.h
Labels: benchmark

#292 Strengthen spec for `montgomery_reduce()`
  cbmc/proofs/fqmul/Makefile
  mlkem/common.h
  mlkem/reduce.c
  mlkem/reduce.h
Labels: benchmark
