Repository pq-code-package/mlkem-native, pull requests merged in 2024-09, with the labels that each got.

#99 Add workflows for benchmarking on EC2
  .github/actions/setup-nix/action.yml
  .github/workflows/bench_ec2_all.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
Labels: benchmark

#101 Push EC2 benchmark results to GH pages
  .github/workflows/bench_ec2_all.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
Labels: benchmark

#100 Refactor Build System for Easier Extensibility and Future Optimizations
  .github/workflows/bench.yml
  .gitignore
  Makefile
  cbmc/litani.nix
  mk/config.mk
  mk/crypto.mk
  mk/hal.mk
  mk/rules.mk
  mk/schemes.mk
  scripts/tests
  test/hal/hal.c
  test/hal/hal.h
Labels: benchmark

#110 Hoist benchmarking steps into reusable Github action
  .github/actions/bench/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
Labels: benchmark

#113 Add cpucap.h header and detect AArch64 systems
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_all.yml
  .github/workflows/ci.yml
  cbmc/proofs/Makefile.common
  mk/schemes.mk
  mlkem/params.h
  mlkem/sys/cpucap.h
Labels: benchmark

#123 CI fixes
  .github/actions/bench/action.yml
  .github/actions/functest/action.yml
  .github/workflows/bench_ec2_all.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_any.yml
  .github/workflows/ci_ec2_reusable.yml
Labels: benchmark

#109 Basic ntt
  mk/config.mk
  mk/schemes.mk
  mlkem/asm/aarch64/common.i
  mlkem/asm/aarch64/intt_123_4567.S
  mlkem/asm/aarch64/intt_kyber_123_45_67_twiddles.S
  mlkem/asm/aarch64/ntt_123_4567.S
  mlkem/asm/aarch64/ntt_kyber_123_45_67_twiddles.S
  mlkem/asm/asm.h
  mlkem/ntt.c
  mlkem/sys/config.h
  scripts/tests
Labels: benchmark

#124 Make AMI ID dropdown
  .github/actions/bench/action.yml
  .github/actions/cbmc/action.yml
  .github/actions/functest/action.yml
  .github/actions/lint/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_all.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci_ec2_any.yml
  .github/workflows/ci_ec2_reusable.yml
Labels: benchmark

#125 Run opt/non-opt in CI
  .github/actions/bench/action.yml
  .github/actions/functest/action.yml
  .github/workflows/bench_ec2_all.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_any.yml
  .github/workflows/ci_ec2_reusable.yml
Labels: benchmark

#126 Disambiguate opt vs non-opt in benchmarking stats
  .github/workflows/bench_ec2_all.yml
Labels: benchmark

#127 Add native x86_64 test to CI
  .github/actions/bench/action.yml
  .github/workflows/bench_ec2_any.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  mlkem/sys/config.h
  scripts/tests
Labels: benchmark

#129 update DeterminateSystems to latest version
  .github/actions/setup-nix/action.yml
Labels: benchmark

#130 X86 64 gcc
  .github/actions/bench/action.yml
  .github/actions/cbmc/action.yml
  .github/actions/functest/action.yml
  .github/actions/lint/action.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci.yml
  .github/workflows/ci_ec2_reusable.yml
  flake.nix
  mk/config.mk
Labels: benchmark

#133 Add scalar AArch64 Keccak-f1600 ASM
  fips202/asm/aarch64/common.i
  fips202/asm/aarch64/keccak_f1600_x1_scalar_opt_a55.S
  fips202/asm/asm.h
  fips202/keccakf1600.c
  fips202/keccakf1600.h
  mk/crypto.mk
  mk/rules.mk
Labels: benchmark

#137 Add batched Keccak ASM
  fips202/asm/aarch64/common.i
  fips202/asm/aarch64/keccak_f1600_x2_v48a_clean.S
  fips202/asm/asm.h
  fips202/fips202x4.c
  fips202/fips202x4.h
  fips202/keccakf1600.c
  fips202/keccakf1600.h
  mlkem/asm/aarch64/common.i
  mlkem/indcpa.c
  mlkem/symmetric-shake.c
  mlkem/symmetric.h
  mlkem/sys/cpucap.h
Labels: benchmark

#139 Add hybrid Neon/Neon Keccak-f1600, don't use scalar ASM on Cortex-A72
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_all.yml
  fips202/asm/aarch64/keccak_f1600_x2_v8a_v84a_hybrid.S
  fips202/asm/asm.h
Labels: benchmark

#142 move bench_ec2_all to bench workflow and only store results for pushing to main event
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_all.yml
Labels: benchmark

#143 Add experimental SLOTHY-optimized NTT
  mlkem/asm/aarch64/intt_123_45_67_twiddles.S
  mlkem/asm/aarch64/intt_clean.S
  mlkem/asm/aarch64/intt_opt.S
  mlkem/asm/aarch64/ntt_123_45_67_twiddles.S
  mlkem/asm/aarch64/ntt_clean.S
  mlkem/asm/aarch64/ntt_opt.S
  mlkem/asm/aarch64/optimize.sh
  mlkem/asm/aarch64/poly_clean.S
  mlkem/asm/aarch64/poly_opt.S
  mlkem/asm/asm.h
  mlkem/ntt.c
  mlkem/poly.c
Labels: benchmark

#153 Use v8.4A-based x1 Keccak-f1600 on Apple CPUs
  fips202/asm/aarch64/keccak_f1600_x1_v84a_clean.S
  fips202/asm/asm.h
Labels: benchmark

#154 Run CBMC on EC2 runner in CI and guard by label
  .github/workflows/ci.yml
Labels: ci

#162 Remove `poly_[inv]ntt -> [inv]ntt()` indirection and unnecessary reduction
  mlkem/ntt.c
  mlkem/ntt.h
  mlkem/poly.c
  mlkem/poly.h
  mlkem/polyvec.c
Labels: benchmark, ci

#170 Add binary for benchmarking MLKEM components
  .github/actions/bench/action.yml
  Makefile
  mk/bench_components.mk
  mk/schemes.mk
  scripts/tests
  test/bench_components_kyber.c
Labels: benchmark, ci
