Repository pq-code-package/mlkem-native, pull requests merged in 2024-06, with the labels that each got.

#46 Demonstrate use of CBMC in example of (de)compression routines
  .github/workflows/build.yml
  cbmc/.gitignore
  cbmc/include/README.md
  cbmc/proofs/Makefile-project-defines
  cbmc/proofs/Makefile-project-targets
  cbmc/proofs/Makefile-project-testing
  cbmc/proofs/Makefile-template-defines
  cbmc/proofs/Makefile.common
  cbmc/proofs/Makefile_params.common
  cbmc/proofs/README.md
  cbmc/proofs/lib/__init__.py
  cbmc/proofs/lib/print_tool_versions.py
  cbmc/proofs/lib/summarize.py
  cbmc/proofs/poly_compress/Makefile
  cbmc/proofs/poly_compress/README.md
  cbmc/proofs/poly_compress/cbmc-proof.txt
  cbmc/proofs/poly_compress/cbmc-viewer.json
  cbmc/proofs/poly_compress/poly_compress_harness.c
  cbmc/proofs/poly_decompress/Makefile
  cbmc/proofs/poly_decompress/README.md
  cbmc/proofs/poly_decompress/cbmc-proof.txt
  cbmc/proofs/poly_decompress/cbmc-viewer.json
  cbmc/proofs/poly_decompress/poly_decompress_harness.c
  cbmc/proofs/run-cbmc-proofs.py
  cbmc/proofs/scalar_compress_q_16/Makefile
  cbmc/proofs/scalar_compress_q_16/README.md
  cbmc/proofs/scalar_compress_q_16/cbmc-proof.txt
  cbmc/proofs/scalar_compress_q_16/cbmc-viewer.json
  cbmc/proofs/scalar_compress_q_16/scalar_compress_q_16_harness.c
  cbmc/proofs/scalar_compress_q_32/Makefile
  cbmc/proofs/scalar_compress_q_32/README.md
  cbmc/proofs/scalar_compress_q_32/cbmc-proof.txt
  cbmc/proofs/scalar_compress_q_32/cbmc-viewer.json
  cbmc/proofs/scalar_compress_q_32/scalar_compress_q_32_harness.c
  cbmc/proofs/scalar_decompress_q_16/Makefile
  cbmc/proofs/scalar_decompress_q_16/README.md
  cbmc/proofs/scalar_decompress_q_16/cbmc-proof.txt
  cbmc/proofs/scalar_decompress_q_16/cbmc-viewer.json
  cbmc/proofs/scalar_decompress_q_16/scalar_decompress_q_16_harness.c
  cbmc/proofs/scalar_decompress_q_32/Makefile
  cbmc/proofs/scalar_decompress_q_32/README.md
  cbmc/proofs/scalar_decompress_q_32/cbmc-proof.txt
  cbmc/proofs/scalar_decompress_q_32/cbmc-viewer.json
  cbmc/proofs/scalar_decompress_q_32/scalar_decompress_q_32_harness.c
  cbmc/sources/README.md
  cbmc/stubs/README.md
  flake.nix
  mlkem/cbmc.h
  mlkem/poly.c
  mlkem/poly.h
  scripts/ci/lint
Labels: enhancement

#69 Add benchmark workflow (RPi4 / Arm Cortex-A72)
  .github/actions/setup-nix/action.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  Makefile
  flake.nix
  scripts/tests
Labels: benchmark

#72 Fix the trigger of bench workflow for PR
  .github/workflows/bench.yml
Labels: benchmark

#71 CBMC: Update to Version 6
  cbmc/proofs/Makefile.common
  cbmc/proofs/poly_compress/poly_compress_harness.c
  cbmc/proofs/poly_decompress/poly_decompress_harness.c
  flake.nix
  mlkem/poly.c
Labels: benchmark

#77 Make the bench workflow trigger more naturally
  .github/workflows/bench.yml
Labels: bug, benchmark

#79 Makefile keep track of variables
  .gitignore
  Makefile
  mk/config.mk
Labels: benchmark

#81 Add M1 benchmarking code
  mk/config.mk
  scripts/tests
  test/hal.c
Labels: benchmark

#82 Add support for static linking of glibc on aarch64 and x86_64 linux
  arm-gnu-gcc.nix
  flake.nix
Labels: benchmark
