Repository pq-code-package/mlkem-native, pull requests merged in 2025-04, with the labels that each got.

#939 CI: Update dependencies
  .github/workflows/base.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci_ec2_container.yml
  .github/workflows/ci_ec2_reusable.yml
  .github/workflows/hol_light.yml
  .github/workflows/scorecard.yaml
Labels: benchmark

#938 Benchmarking: Re-enable MacMini
  .github/actions/functest/action.yml
  .github/actions/lint/action.yml
  .github/actions/multi-functest/action.yml
  .github/workflows/bench.yml
Labels: benchmark

#942 Simplify mlkem_native.h
  examples/bring_your_own_fips202/Makefile
  examples/bring_your_own_fips202/main.c
  examples/custom_backend/Makefile
  examples/custom_backend/main.c
  examples/custom_backend/mlkem_native/custom_config.h
  examples/mlkem_native_as_code_package/Makefile
  examples/mlkem_native_as_code_package/main.c
  examples/monolithic_build/Makefile
  examples/monolithic_build/main.c
  examples/monolithic_build/mlkem_native_monobuild.c
  examples/monolithic_build_multilevel/README.md
  examples/monolithic_build_multilevel/mlkem_native_all.c
  examples/monolithic_build_multilevel/mlkem_native_all.h
  examples/monolithic_build_multilevel_native/Makefile
  examples/monolithic_build_multilevel_native/README.md
  examples/monolithic_build_multilevel_native/main.c
  examples/monolithic_build_multilevel_native/mlkem_native_all.c
  examples/monolithic_build_multilevel_native/mlkem_native_all.h
  examples/multilevel_build/mlkem_native_all.h
  examples/multilevel_build_native/mlkem_native_all.h
  mlkem/common.h
  mlkem/kem.h
  mlkem/mlkem_native.h
  scripts/autogen
  test/acvp_mlkem.c
  test/bench_mlkem.c
Labels: benchmark

#947 Add and apply "InsertBraces" option for clang-format
  .clang-format
  dev/x86_64/src/rej_uniform_avx2.c
  examples/bring_your_own_fips202/custom_fips202/tiny_sha3/sha3.c
  examples/bring_your_own_fips202/main.c
  examples/custom_backend/main.c
  examples/custom_backend/mlkem_native/mlkem/fips202/native/custom/src/sha3.c
  examples/mlkem_native_as_code_package/main.c
  examples/monolithic_build/main.c
  examples/monolithic_build_multilevel/main.c
  examples/monolithic_build_multilevel_native/main.c
  examples/multilevel_build/main.c
  examples/multilevel_build_native/main.c
  mlkem/debug.c
  mlkem/native/x86_64/src/rej_uniform_avx2.c
  test/bench_mlkem.c
Labels: enhancement

#952 Adjust SLOTHY README
  dev/aarch64_opt/src/README.md
Labels: documentation, enhancement

#654 Add AWS-LC integration test
  .github/actions/setup-aws-lc/action.yml
  .github/workflows/all.yml
  .github/workflows/integration-awslc.yml
Labels: integration

#987 API header: Refer to examples using mlkem_native.h
  mlkem/mlkem_native.h
Labels: documentation, enhancement
