Repository pq-code-package/mlkem-native, pull requests merged in 2025-03, with the labels that each got.

#822 FIPS202/AArch64: Interleave first iteration in triple hybrid Keccak
  dev/fips202/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
Labels: benchmark

#677 NTT: Simplify computation of zeta index
  .github/workflows/base.yml
  .github/workflows/bench_ec2_reusable.yml
  .github/workflows/ci_ec2_container.yml
  .github/workflows/ci_ec2_reusable.yml
  .github/workflows/scorecard.yaml
  mlkem/poly.c
  proofs/cbmc/invntt_layer/invntt_layer_harness.c
  proofs/cbmc/ntt_layer/ntt_layer_harness.c
  test/mk/rules.mk
Labels: benchmark

#831 CI/HOL-Light: Only run proof if respective files have changed
  .github/workflows/hol_light.yml
  README.md
  dev/fips202/aarch64/src/cortex_a55_impl.h
  dev/fips202/aarch64/src/default_impl.h
  dev/fips202/aarch64/src/fips202_native_aarch64.h
  dev/fips202/aarch64/src/keccak_f1600_x1_scalar_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x1_v84a_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x2_v84a_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid.S
  dev/fips202/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm.S
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/fips202/native/aarch64/src/cortex_a55_impl.h
  mlkem/fips202/native/aarch64/src/default_impl.h
  mlkem/fips202/native/aarch64/src/fips202_native_aarch64.h
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_scalar_asm.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v84a_asm.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm.S
  proofs/hol_light/arm/Makefile
  proofs/hol_light/arm/mlkem/keccak_f1600_x1_scalar.S
  proofs/hol_light/arm/mlkem/keccak_f1600_x1_v84a.S
  proofs/hol_light/arm/proofs/keccak_f1600_x1_scalar.ml
  proofs/hol_light/arm/proofs/keccak_f1600_x1_v84a.ml
  scripts/autogen
Labels: benchmark

#837 Rename -c M1 option to -c MAC
  .github/workflows/base.yml
  BUILDING.md
  Makefile
  scripts/tests
  test/hal/hal.c
  test/mk/config.mk
Labels: benchmark

#862 Remove CLEAN and OPT suffixes from MLK_ARITH_BACKEND_AARCH64 macro
  dev/aarch64_clean/meta.h
  dev/aarch64_clean/src/aarch64_zetas.c
  dev/aarch64_clean/src/intt.S
  dev/aarch64_clean/src/ntt.S
  dev/aarch64_clean/src/poly_mulcache_compute_asm.S
  dev/aarch64_clean/src/poly_reduce_asm.S
  dev/aarch64_clean/src/poly_tobytes_asm.S
  dev/aarch64_clean/src/poly_tomont_asm.S
  dev/aarch64_clean/src/polyvec_basemul_acc_montgomery_cached_asm_k2.S
  dev/aarch64_clean/src/polyvec_basemul_acc_montgomery_cached_asm_k3.S
  dev/aarch64_clean/src/polyvec_basemul_acc_montgomery_cached_asm_k4.S
  dev/aarch64_clean/src/rej_uniform_asm.S
  dev/aarch64_clean/src/rej_uniform_table.c
  dev/aarch64_opt/meta.h
  dev/aarch64_opt/src/aarch64_zetas.c
  dev/aarch64_opt/src/intt.S
  dev/aarch64_opt/src/ntt.S
  dev/aarch64_opt/src/poly_mulcache_compute_asm.S
  dev/aarch64_opt/src/poly_reduce_asm.S
  dev/aarch64_opt/src/poly_tobytes_asm.S
  dev/aarch64_opt/src/poly_tomont_asm.S
  dev/aarch64_opt/src/polyvec_basemul_acc_montgomery_cached_asm_k2.S
  dev/aarch64_opt/src/polyvec_basemul_acc_montgomery_cached_asm_k3.S
  dev/aarch64_opt/src/polyvec_basemul_acc_montgomery_cached_asm_k4.S
  dev/aarch64_opt/src/rej_uniform_asm.S
  dev/aarch64_opt/src/rej_uniform_table.c
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/native/aarch64/meta.h
  mlkem/native/aarch64/src/aarch64_zetas.c
  mlkem/native/aarch64/src/intt.S
  mlkem/native/aarch64/src/ntt.S
  mlkem/native/aarch64/src/poly_mulcache_compute_asm.S
  mlkem/native/aarch64/src/poly_reduce_asm.S
  mlkem/native/aarch64/src/poly_tobytes_asm.S
  mlkem/native/aarch64/src/poly_tomont_asm.S
  mlkem/native/aarch64/src/polyvec_basemul_acc_montgomery_cached_asm_k2.S
  mlkem/native/aarch64/src/polyvec_basemul_acc_montgomery_cached_asm_k3.S
  mlkem/native/aarch64/src/polyvec_basemul_acc_montgomery_cached_asm_k4.S
  mlkem/native/aarch64/src/rej_uniform_asm.S
  mlkem/native/aarch64/src/rej_uniform_table.c
  scripts/autogen
  test/bench_components_mlkem.c
Labels: benchmark

#866 Add Apple M1 Mac Mini (2020) to benchmarking CI
  .github/workflows/bench.yml
Labels: benchmark

#834 CBMC: Pull and test weakening is_fresh in contract applications
  examples/monolithic_build/mlkem_native_monobuild.c
  flake.nix
  mlkem/indcpa.c
  mlkem/poly_k.c
  mlkem/poly_k.h
  mlkem/sampling.c
  mlkem/sampling.h
  mlkem/symmetric.h
  mlkem/sys.h
  nix/cbmc/default.nix
  proofs/cbmc/poly_rej_uniform_x4/poly_rej_uniform_x4_harness.c
  test/bench_components_mlkem.c
Labels: benchmark

#882 nix: Use `main` branch of s2n-bignum
  nix/s2n_bignum/default.nix
Labels: hol-light

#773 Faster INTT on AArch64 by more efficient reduction
  dev/aarch64_clean/src/intt.S
  dev/aarch64_opt/src/intt.S
  mlkem/native/aarch64/src/intt.S
  proofs/hol_light/arm/mlkem/mlkem_intt.S
  proofs/hol_light/arm/proofs/mlkem_intt.ml
Labels: benchmark, aarch64

#897 Switch mlkem_poly_basemul_acc_montgomery_cached_* proofs to integer specs
  .github/workflows/hol_light.yml
  README.md
  proofs/hol_light/arm/README.md
  proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k2.ml
  proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k3.ml
  proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k4.ml
  proofs/hol_light/arm/proofs/mlkem_specs.ml
Labels: hol-light

#900 HOL-Light: Autogenerate zeta tables in proof scripts
  .github/workflows/hol_light.yml
  proofs/hol_light/arm/proofs/mlkem_intt.ml
  proofs/hol_light/arm/proofs/mlkem_ntt.ml
  proofs/hol_light/arm/proofs/mlkem_zetas.ml
  scripts/autogen
Labels: enhancement, hol-light

#901 Update and extend README's on formal verification
  README.md
  proofs/README.md
  proofs/cbmc/README.md
  proofs/hol_light/arm/README.md
Labels: documentation

#904 CBMC: Add a link to list of undefined behaviors caught by CBMC
  proofs/cbmc/README.md
Labels: CBMC

#905 CBMC tests: Allow wildcard pattern in list of proofs to run
  scripts/tests
Labels: enhancement, CBMC

#895 Define `mlk_polyvec[_mulcache]` as typedef for array
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/indcpa.c
  mlkem/indcpa.h
  mlkem/kem.c
  mlkem/poly_k.c
  mlkem/poly_k.h
  proofs/cbmc/gen_matrix/Makefile
  proofs/cbmc/gen_matrix/gen_matrix_harness.c
  proofs/cbmc/gen_matrix_native/Makefile
  proofs/cbmc/gen_matrix_native/gen_matrix_native_harness.c
  proofs/cbmc/matvec_mul/matvec_mul_harness.c
  proofs/cbmc/polyvec_add/polyvec_add_harness.c
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached/polyvec_basemul_acc_montgomery_cached_harness.c
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_native/polyvec_basemul_acc_montgomery_cached_native_harness.c
  proofs/cbmc/polyvec_compress_du/polyvec_compress_du_harness.c
  proofs/cbmc/polyvec_decompress_du/polyvec_decompress_du_harness.c
  proofs/cbmc/polyvec_frombytes/polyvec_frombytes_harness.c
  proofs/cbmc/polyvec_invntt_tomont/polyvec_invntt_tomont_harness.c
  proofs/cbmc/polyvec_mulcache_compute/polyvec_mulcache_compute_harness.c
  proofs/cbmc/polyvec_ntt/polyvec_ntt_harness.c
  proofs/cbmc/polyvec_reduce/polyvec_reduce_harness.c
  proofs/cbmc/polyvec_tobytes/polyvec_tobytes_harness.c
  proofs/cbmc/polyvec_tomont/polyvec_tomont_harness.c
  test/bench_components_mlkem.c
Labels: benchmark

#914 CBMC: Remove unused array parameters
  proofs/cbmc/keccak_squeeze_once/Makefile
  proofs/cbmc/keccak_squeezeblocks/Makefile
  proofs/cbmc/keccak_squeezeblocks_x4/Makefile
  proofs/cbmc/keccakf1600_extract_bytes/Makefile
  proofs/cbmc/keccakf1600_permute/Makefile
  proofs/cbmc/keccakf1600x4_extract_bytes/Makefile
  proofs/cbmc/keccakf1600x4_permute/Makefile
  proofs/cbmc/matvec_mul/Makefile
  proofs/cbmc/poly_permute_bitrev_to_custom/Makefile
  proofs/cbmc/polyvec_add/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached/Makefile
  proofs/cbmc/rej_uniform_native/Makefile
Labels: enhancement, CBMC
