Repository pq-code-package/mlkem-native, pull requests merged in 2025-07, with the labels that each got.

#1097 AVX2 implementation of polyvec_basemul in assembly
  BIBLIOGRAPHY.md
  dev/x86_64/meta.h
  dev/x86_64/src/arith_native_x86_64.h
  dev/x86_64/src/basemul.S
  dev/x86_64/src/basemul.c
  dev/x86_64/src/poly_basemul.inc
  dev/x86_64/src/polyvec_basemul_acc_montgomery_cached_asm_k2.S
  dev/x86_64/src/polyvec_basemul_acc_montgomery_cached_asm_k3.S
  dev/x86_64/src/polyvec_basemul_acc_montgomery_cached_asm_k4.S
  mlkem/mlkem_native.S
  mlkem/mlkem_native.c
  mlkem/src/native/x86_64/meta.h
  mlkem/src/native/x86_64/src/arith_native_x86_64.h
  mlkem/src/native/x86_64/src/basemul.S
  mlkem/src/native/x86_64/src/basemul.c
  mlkem/src/native/x86_64/src/poly_basemul.inc
  mlkem/src/native/x86_64/src/polyvec_basemul_acc_montgomery_cached_asm_k2.S
  mlkem/src/native/x86_64/src/polyvec_basemul_acc_montgomery_cached_asm_k3.S
  mlkem/src/native/x86_64/src/polyvec_basemul_acc_montgomery_cached_asm_k4.S
Labels: benchmark

#1108 lint, autogen, format: Improve and unify UX
  scripts/autogen
  scripts/format
  scripts/lint
Labels: needs-mldsa-native-port

#1109 CBMC: Fix mistakes in proof guide
  proofs/cbmc/proof_guide.md
Labels: documentation, CBMC

#1112 Simplify gen_matrix() and poly_rej_uniform_x4()
  mlkem/src/indcpa.c
  mlkem/src/sampling.c
  mlkem/src/sampling.h
  proofs/cbmc/poly_rej_uniform_x4/poly_rej_uniform_x4_harness.c
  test/bench_components_mlkem.c
Labels: benchmark

#1124 Update CBMC proof guide and README to include installation instructions
  proofs/cbmc/README.md
  proofs/cbmc/proof_guide.md
Labels: needs-mldsa-native-port

#1089 Measure code-size
  Makefile
  examples/basic/Makefile
  examples/bring_your_own_fips202/Makefile
  examples/custom_backend/Makefile
  examples/monolithic_build/Makefile
  examples/monolithic_build_multilevel/Makefile
  examples/monolithic_build_multilevel_native/Makefile
  examples/monolithic_build_native/Makefile
  examples/multilevel_build/Makefile
  examples/multilevel_build_native/Makefile
  scripts/tests
Labels: benchmark

#1131 Makefile: Detect suitable sha256sum tool and set `-o pipefail`
  Makefile
Labels: needs-mldsa-native-port
