Repository pq-code-package/mlkem-native, pull requests merged in 2025-01, with the labels that each got.

#608 Makefile: Fix race condition during duplicated symbol checking
  mk/rules.mk
Labels: bug, build

#602 Makefile: Don't include HAL into libmlkem.a when building benchmarks
  Makefile
  mk/bench.mk
  mk/bench_components.mk
  mk/schemes.mk
Labels: benchmark

#606 README: Minor improvement to Ubuntu quickstart
  README.md
Labels: documentation, enhancement

#599 Makefile: Minor cleanup and introduction of level-specific targets
  Makefile
  mk/components.mk
  mk/crypto.mk
  scripts/lib/mlkem_test.py
  scripts/lib/util.py
Labels: benchmark

#605 Make `tests` a shallow wrapper around `make`
  BUILDING.md
  Makefile
  README.md
  mk/rules.mk
  scripts/lib/mlkem_test.py
  scripts/lib/util.py
  scripts/tests
Labels: benchmark

#616 Format: Ignore symlinks
  scripts/format
Labels: bug, build

#617 CI: Generalize compiler test to exercise various C standards
  .github/actions/functest/action.yml
  .github/workflows/ci.yml
Labels: enhancement, ci

#631 CBMC: Use exclusive upper bounds for `forall` primitive
  mlkem/cbd.c
  mlkem/cbd.h
  mlkem/cbmc.h
  mlkem/indcpa.c
  mlkem/indcpa.h
  mlkem/ntt.c
  mlkem/ntt.h
  mlkem/poly.c
  mlkem/poly.h
  mlkem/polyvec.c
  mlkem/polyvec.h
  mlkem/rej_uniform.c
  mlkem/rej_uniform.h
  mlkem/verify.h
Labels: CBMC

#629 CBMC: Big-endian proofs for KeccakF1600_State{Extract,XOR}Bytes
  cbmc/KeccakF1600_StateExtractBytes_BE/KeccakF1600_StateExtractBytes_be_harness.c
  cbmc/KeccakF1600_StateExtractBytes_BE/Makefile
  cbmc/KeccakF1600_StateExtractBytes_BE/cbmc-proof.txt
  cbmc/KeccakF1600_StateXORBytes_BE/KeccakF1600_StateXORBytes_be_harness.c
  cbmc/KeccakF1600_StateXORBytes_BE/Makefile
  cbmc/KeccakF1600_StateXORBytes_BE/cbmc-proof.txt
  cbmc/run-cbmc-proofs.py
  mlkem/fips202/keccakf1600.c
  mlkem/sys.h
Labels: CBMC

#637 CBMC: Switch to exclusive coefficient upper bounds
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/cbd.c
  mlkem/cbd.h
  mlkem/cbmc.h
  mlkem/indcpa.c
  mlkem/indcpa.h
  mlkem/ntt.c
  mlkem/ntt.h
  mlkem/params.h
  mlkem/poly.c
  mlkem/poly.h
  mlkem/polyvec.c
  mlkem/polyvec.h
  mlkem/reduce.h
  mlkem/rej_uniform.c
  mlkem/rej_uniform.h
Labels: CBMC

#636 CBMC: Update proof guide
  cbmc/proof_guide.md
Labels: enhancement, CBMC

#651 Fix includes in benchmarks
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  examples/custom_backend/Makefile
  mlkem/fips202/fips202_backend.h
  mlkem/fips202/native/x86_64/xkcp.h
  test/bench_components_mlkem.c
  test/bench_mlkem.c
Labels: benchmark

#649 Remove (almost) all macros with leading underscore
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/common.h
  mlkem/fips202/native/x86_64/src/KeccakP-1600-times4-SnP.h
  mlkem/fips202/native/x86_64/src/KeccakP-align.h
  mlkem/fips202/native/x86_64/src/KeccakP-brg_endian.h
  mlkem/native/x86_64/src/basemul.S
  mlkem/native/x86_64/src/consts.c
  mlkem/native/x86_64/src/consts.h
  mlkem/native/x86_64/src/fq.S
  mlkem/native/x86_64/src/intt.S
  mlkem/native/x86_64/src/ntt.S
  mlkem/native/x86_64/src/rej_uniform_avx2.c
  mlkem/native/x86_64/src/shuffle.S
  scripts/autogen
Labels: benchmark

#657 Fix `tests bench [--opt=ALL]` so it runs opt and non-opt benchmarks
  scripts/tests
Labels: benchmark

#664 CBMC: Remove redundant `0 <= ...` assertions in loop invariants
  mlkem/cbd.c
  mlkem/cbmc.h
  mlkem/fips202/keccakf1600.c
  mlkem/indcpa.c
  mlkem/ntt.c
  mlkem/poly.c
  mlkem/verify.h
  proofs/cbmc/invntt_layer/invntt_layer_harness.c
  proofs/cbmc/ntt_butterfly_block/ntt_butterfly_block_harness.c
  proofs/cbmc/ntt_layer/ntt_layer_harness.c
  proofs/cbmc/proof_guide.md
Labels: enhancement, CBMC

#666 Turn debug assertions into CBMC constraints when CBMC is used
  README.md
  RELEASE.md
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/cbmc.h
  mlkem/debug/debug.h
  mlkem/indcpa.c
  mlkem/poly.c
  mlkem/poly.h
  mlkem/polyvec.c
  mlkem/reduce.h
  mlkem/rej_uniform.c
  proofs/cbmc/poly_basemul_montgomery_cached/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached/Makefile
  proofs/cbmc/polyvec_compress_du/Makefile
Labels: enhancement, CBMC

#659 autogen: Add checker for dangling register aliases in assembly files
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_scalar_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v84a_asm_clean.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v8a_v84a_asm_hybrid.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
  mlkem/native/aarch64/src/intt_clean.S
  mlkem/native/aarch64/src/intt_opt.S
  mlkem/native/aarch64/src/ntt_clean.S
  mlkem/native/aarch64/src/ntt_opt.S
  mlkem/native/aarch64/src/polyvec_clean.S
  mlkem/native/aarch64/src/polyvec_opt.S
  mlkem/native/aarch64/src/rej_uniform_asm_clean.S
  scripts/autogen
Labels: benchmark

#667 AArch64: Remove literal pools from native code
  mlkem/native/aarch64/src/intt_clean.S
  mlkem/native/aarch64/src/intt_opt.S
  mlkem/native/aarch64/src/ntt_clean.S
  mlkem/native/aarch64/src/ntt_opt.S
  mlkem/native/aarch64/src/poly_clean.S
  mlkem/native/aarch64/src/poly_opt.S
  mlkem/native/aarch64/src/polyvec_clean.S
  mlkem/native/aarch64/src/polyvec_opt.S
  mlkem/native/aarch64/src/rej_uniform_asm_clean.S
Labels: benchmark

#675 Backend API: Remove dependence on poly_* structs
  mlkem/compress.c
  mlkem/indcpa.c
  mlkem/native/aarch64/src/clean_impl.h
  mlkem/native/aarch64/src/opt_impl.h
  mlkem/native/api.h
  mlkem/native/x86_64/src/arith_native_x86_64.h
  mlkem/native/x86_64/src/basemul.c
  mlkem/native/x86_64/src/default_impl.h
  mlkem/poly.c
  mlkem/poly_k.c
Labels: benchmark

#684 Make arithmetic and FIPS202 backends independently configurable
  .github/workflows/bench.yml
  examples/custom_backend/mlkem_native/custom_config.h
  examples/monolithic_build/config_512.h
  examples/monolithic_build/mlkem_native_monobuild.c
  examples/monolithic_build_multilevel/config_1024.h
  examples/monolithic_build_multilevel/config_512.h
  examples/monolithic_build_multilevel/config_768.h
  integration/liboqs/ML-KEM-1024_META.yml
  integration/liboqs/ML-KEM-512_META.yml
  integration/liboqs/ML-KEM-768_META.yml
  mlkem/common.h
  mlkem/config.h
  test/mk/components.mk
Labels: benchmark

#697 Specify -march= for x86 benchmarks
  .github/workflows/bench.yml
Labels: benchmark

#698 Fix component benchmarks
  .github/actions/bench/action.yml
  scripts/tests
  test/bench_components_mlkem.c
Labels: benchmark

#699 Fix exec wrapper for `tests bench --components`
  .github/actions/bench/action.yml
Labels: benchmark

#703 Add balign to all AArch64 asm
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_scalar_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
  mlkem/native/aarch64/src/intt_clean.S
  mlkem/native/aarch64/src/intt_opt.S
  mlkem/native/aarch64/src/ntt_clean.S
  mlkem/native/aarch64/src/ntt_opt.S
  mlkem/native/aarch64/src/poly_clean.S
  mlkem/native/aarch64/src/poly_opt.S
  mlkem/native/aarch64/src/polyvec_clean.S
  mlkem/native/aarch64/src/polyvec_opt.S
  mlkem/native/aarch64/src/rej_uniform_asm_clean.S
Labels: benchmark

#705 Add alignment constraint to stack buffer in rejection sampling
  mlkem/sampling.c
Labels: benchmark

#706 Don't emit dummy definitions in empty CUs
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/common.h
  mlkem/compress.c
  mlkem/debug.c
  mlkem/fips202/fips202.c
  mlkem/fips202/fips202x4.c
  mlkem/fips202/keccakf1600.c
  mlkem/fips202/native/aarch64/src/keccakf1600_round_constants.c
  mlkem/fips202/native/x86_64/src/KeccakP-1600-times4-SIMD256.c
  mlkem/kem.c
  mlkem/native/aarch64/src/aarch64_zetas.c
  mlkem/native/aarch64/src/rej_uniform_table.c
  mlkem/native/x86_64/src/basemul.c
  mlkem/native/x86_64/src/consts.c
  mlkem/native/x86_64/src/rej_uniform_avx2.c
  mlkem/native/x86_64/src/rej_uniform_table.c
  mlkem/poly.c
  mlkem/sampling.c
  mlkem/verify.c
  mlkem/zetas.c
  scripts/autogen
Labels: benchmark

#709 Add AVX2 native polynomial compress/decompression
  mlkem/compress.c
  mlkem/native/api.h
  mlkem/native/x86_64/src/arith_native_x86_64.h
  mlkem/native/x86_64/src/compress_avx2.c
  mlkem/native/x86_64/src/default_impl.h
  test/test_mlkem.c
Labels: benchmark

#626 Use Keccak-x4 in poly_getnoise_eta1122_4x
  examples/custom_backend/mlkem_native/mlkem/fips202/native/custom/src/custom_impl.h
  examples/custom_backend/mlkem_native/mlkem/fips202/native/custom/src/sha3.c
  examples/custom_backend/mlkem_native/mlkem/fips202/native/custom/src/sha3.h
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/fips202/fips202.h
  mlkem/poly_k.c
  proofs/cbmc/poly_getnoise_eta1122_4x_native/Makefile
  proofs/cbmc/poly_getnoise_eta1122_4x_native/cbmc-proof.txt
  proofs/cbmc/poly_getnoise_eta1122_4x_native/poly_getnoise_eta1122_4x_native_harness.c
Labels: benchmark

#723 Nix: switch default compiler to gcc14
  .github/workflows/ci.yml
  nix/util.nix
Labels: benchmark
