Repository pq-code-package/mlkem-native, pull requests merged in 2025-05, with the labels that each got.

#991 Fix reporting of total proof count from upstream cbmc-starter-kit repo
  proofs/cbmc/lib/summarize.py
Labels: CBMC

#996 AVX2 basemul with mulcache
  dev/x86_64/meta.h
  dev/x86_64/src/arith_native_x86_64.h
  dev/x86_64/src/basemul.S
  dev/x86_64/src/basemul.c
  dev/x86_64/src/consts.c
  dev/x86_64/src/consts.h
  dev/x86_64/src/mulcache_compute.S
  dev/x86_64/src/x86_64_mulcache_twiddles.i
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/native/api.h
  mlkem/native/x86_64/meta.h
  mlkem/native/x86_64/src/arith_native_x86_64.h
  mlkem/native/x86_64/src/basemul.S
  mlkem/native/x86_64/src/basemul.c
  mlkem/native/x86_64/src/consts.c
  mlkem/native/x86_64/src/consts.h
  mlkem/native/x86_64/src/mulcache_compute.S
  mlkem/native/x86_64/src/x86_64_mulcache_twiddles.i
  mlkem/poly.c
  scripts/autogen
Labels: benchmark

#1000 AArch64: Zeroize rejection sampling stack buffer
  dev/aarch64_clean/src/rej_uniform_asm.S
  dev/aarch64_opt/src/rej_uniform_asm.S
  mlkem/native/aarch64/src/rej_uniform_asm.S
Labels: benchmark

#1004 AArch64: Interleave first iteration of hybrid Neon/scalar Keccak
  dev/fips202/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
  proofs/hol_light/arm/mlkem/keccak_f1600_x4_v8a_scalar.S
  proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_scalar.ml
Labels: benchmark

#1014 HOL-Light: Autogenerate rejection sampling constant table
  .github/workflows/hol_light.yml
  dev/aarch64_clean/src/rej_uniform_table.c
  dev/aarch64_opt/src/rej_uniform_table.c
  mlkem/native/aarch64/src/rej_uniform_table.c
  proofs/hol_light/arm/proofs/mlkem_rej_uniform.ml
  proofs/hol_light/arm/proofs/mlkem_rej_uniform_table.ml
  scripts/autogen
Labels: enhancement, hol-light

#1026 Fix API consistency check for backends
  mlkem/common.h
Labels: bug, benchmark

#1028 CBMC: Prove AArch64 native API for basemul atop HOL-Light spec
  dev/aarch64_clean/src/arith_native_aarch64.h
  dev/aarch64_opt/src/arith_native_aarch64.h
  mlkem/native/aarch64/src/arith_native_aarch64.h
  mlkem/native/api.h
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k2_native_aarch64/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k2_native_aarch64/polyvec_basemul_acc_montgomery_cached_k2_native_aarch64_harness.c
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k3_native_aarch64/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k3_native_aarch64/polyvec_basemul_acc_montgomery_cached_k3_native_aarch64_harness.c
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k4_native_aarch64/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k4_native_aarch64/polyvec_basemul_acc_montgomery_cached_k4_native_aarch64_harness.c
  proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k2.ml
  proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k3.ml
  proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k4.ml
Labels: enhancement, CBMC, aarch64

#1039 CBMC: Don't declare structures in harnesses
  proofs/cbmc/poly_permute_bitrev_to_custom/poly_permute_bitrev_to_custom_harness.c
  proofs/cbmc/poly_rej_uniform_x4/poly_rej_uniform_x4_harness.c
Labels: bug, CBMC

#1041 Update to nixpkgs 25.05
  .github/workflows/all.yml
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  nix/cbmc/0001-Do-not-download-sources-in-cmake.patch
  nix/cbmc/0002-Do-not-download-sources-in-cmake.patch
  nix/cbmc/default.nix
  nix/slothy/default.nix
  nix/util.nix
Labels: benchmark

#1064 nix: Simplify CBMC build
  flake.lock
  flake.nix
  nix/cbmc/0001-Do-not-download-sources-in-cmake.patch
  nix/cbmc/0002-Do-not-download-sources-in-cmake.patch
  nix/cbmc/default.nix
Labels: needs-mldsa-native-port
