Repository pq-code-package/mlkem-native, pull requests merged in 2025-02, with the labels that each got.

#727 Simplify base multiplication
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/poly.c
  mlkem/poly.h
  mlkem/poly_k.c
  mlkem/poly_k.h
  proofs/cbmc/basemul_cached/Makefile
  proofs/cbmc/basemul_cached/basemul_cached_harness.c
  proofs/cbmc/basemul_cached/cbmc-proof.txt
  proofs/cbmc/poly_basemul_montgomery_cached/Makefile
  proofs/cbmc/poly_basemul_montgomery_cached/cbmc-proof.txt
  proofs/cbmc/poly_basemul_montgomery_cached/poly_basemul_montgomery_cached_harness.c
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached/Makefile
  test/bench_components_mlkem.c
Labels: benchmark

#738 Various improvements and fixes to examples/*native
  examples/bring_your_own_fips202/main.c
  examples/bring_your_own_fips202/test_only_rng/notrandombytes.c
  examples/bring_your_own_fips202/test_only_rng/notrandombytes.h
  examples/custom_backend/main.c
  examples/custom_backend/test_only_rng/notrandombytes.c
  examples/custom_backend/test_only_rng/notrandombytes.h
  examples/mlkem_native_as_code_package/main.c
  examples/mlkem_native_as_code_package/test_only_rng/notrandombytes.c
  examples/mlkem_native_as_code_package/test_only_rng/notrandombytes.h
  examples/monolithic_build/main.c
  examples/monolithic_build/test_only_rng/notrandombytes.c
  examples/monolithic_build/test_only_rng/notrandombytes.h
  examples/monolithic_build_multilevel/main.c
  examples/monolithic_build_multilevel/test_only_rng/notrandombytes.c
  examples/monolithic_build_multilevel/test_only_rng/notrandombytes.h
  examples/monolithic_build_multilevel_native/Makefile
  examples/monolithic_build_multilevel_native/main.c
  examples/monolithic_build_multilevel_native/test_only_rng/notrandombytes.c
  examples/monolithic_build_multilevel_native/test_only_rng/notrandombytes.h
  examples/multilevel_build/main.c
  examples/multilevel_build/test_only_rng/notrandombytes.c
  examples/multilevel_build/test_only_rng/notrandombytes.h
  examples/multilevel_build_native/Makefile
  examples/multilevel_build_native/main.c
  examples/multilevel_build_native/test_only_rng/notrandombytes.c
  examples/multilevel_build_native/test_only_rng/notrandombytes.h
  mlkem/native/aarch64/src/opt_impl.h
  mlkem/native/api.h
  mlkem/native/x86_64/src/arith_native_x86_64.h
  mlkem/native/x86_64/src/basemul.c
  mlkem/native/x86_64/src/compress_avx2.c
  mlkem/native/x86_64/src/consts.c
  mlkem/native/x86_64/src/consts.h
  mlkem/native/x86_64/src/default_impl.h
  mlkem/native/x86_64/src/nttfrombytes.S
  mlkem/native/x86_64/src/nttpack.S
  mlkem/native/x86_64/src/ntttobytes.S
  mlkem/native/x86_64/src/nttunpack.S
  mlkem/native/x86_64/src/reduce.S
  mlkem/poly_k.c
  proofs/cbmc/polyvec_basemul_acc_montgomery_cached_native/Makefile
  scripts/autogen
  scripts/tests
  test/aarch64_clean/src/clean_impl.h
  test/notrandombytes/notrandombytes.c
  test/notrandombytes/notrandombytes.h
  test/test_mlkem.c
Labels: benchmark

#739 simpasm: Make AArch64 Keccak assembly amenable to `simpasm`
  .github/workflows/ci.yml
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_scalar_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v84a_asm_clean.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v8a_v84a_asm_hybrid.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm_opt.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
Labels: benchmark

#742 Benchmarking: Use vector instructions on Banana Pi F3
  .github/workflows/bench.yml
Labels: benchmark

#747 Benchmarks: Switch to ci_gcc14 shell instead of ci
  .github/actions/bench/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_reusable.yml
Labels: benchmark

#750 Benchmarks: Add new benchmarking shell
  .github/actions/bench/action.yml
  .github/workflows/bench.yml
  .github/workflows/bench_ec2_reusable.yml
  flake.nix
Labels: benchmark

#752 Various namespacing changes
  dev/x86_64/src/align.h
  dev/x86_64/src/arith_native_x86_64.h
  dev/x86_64/src/basemul.S
  dev/x86_64/src/compress_avx2.c
  dev/x86_64/src/consts.c
  dev/x86_64/src/consts.h
  dev/x86_64/src/default_impl.h
  dev/x86_64/src/intt.S
  dev/x86_64/src/ntt.S
  dev/x86_64/src/nttfrombytes.S
  dev/x86_64/src/ntttobytes.S
  dev/x86_64/src/reduce.S
  dev/x86_64/src/rej_uniform_avx2.c
  dev/x86_64/src/tomont.S
  examples/monolithic_build/mlkem_native_monobuild.c
  examples/monolithic_build_multilevel/mlkem_native_all.c
  examples/monolithic_build_multilevel_native/mlkem_native_all.c
  mlkem/cbmc.h
  mlkem/native/api.h
  mlkem/native/x86_64/src/align.h
  mlkem/native/x86_64/src/arith_native_x86_64.h
  mlkem/native/x86_64/src/compress_avx2.c
  mlkem/native/x86_64/src/consts.c
  mlkem/native/x86_64/src/consts.h
  mlkem/native/x86_64/src/default_impl.h
  mlkem/native/x86_64/src/rej_uniform_avx2.c
  mlkem/poly.c
  mlkem/poly.h
  mlkem/poly_k.c
  mlkem/poly_k.h
  proofs/cbmc/proof_guide.md
  scripts/autogen
Labels: benchmark

#760 Remove polyvec_basemul_acc_montgomery
  examples/monolithic_build/mlkem_native_monobuild.c
  mlkem/indcpa.c
  mlkem/poly.h
  mlkem/poly_k.c
  mlkem/poly_k.h
  mlkem/sys.h
  proofs/cbmc/indcpa_dec/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery/Makefile
  proofs/cbmc/polyvec_basemul_acc_montgomery/cbmc-proof.txt
  proofs/cbmc/polyvec_basemul_acc_montgomery/polyvec_basemul_acc_montgomery_harness.c
Labels: benchmark

#791 CI: temporarily disable A72, A55, BPi
  .github/workflows/bench.yml
Labels: benchmark

#795 Renable benchmarks on A72, A55, BPi
  .github/workflows/bench.yml
Labels: benchmark

#765 Upgrade nix to use 24.11 channel
  .github/actions/cbmc/action.yml
  .github/actions/setup-nix/action.yml
  .github/workflows/ci_ec2_reusable.yml
  .github/workflows/ct-tests.yml
  .github/workflows/nix.yml
  flake.lock
  flake.nix
  nix/cbmc/default.nix
  nix/util.nix
  scripts/simpasm
  test/mk/auto.mk
  test/mk/rules.mk
Labels: benchmark

#799 Document relation to reference implementation
  REFERENCE.md
  mlkem/compress.c
  mlkem/compress.h
  mlkem/indcpa.c
  mlkem/kem.c
  mlkem/poly.c
  mlkem/poly_k.c
  mlkem/sampling.c
  mlkem/verify.h
Labels: documentation, enhancement

#803 CBMC: Add contract checker
  mlkem/verify.h
  proofs/cbmc/ct_get_optblocker_i32/Makefile
  proofs/cbmc/ct_get_optblocker_i32/ct_get_optblocker_i32_harness.c
  proofs/cbmc/ct_get_optblocker_u32/Makefile
  proofs/cbmc/ct_get_optblocker_u32/ct_get_optblocker_u32_harness.c
  proofs/cbmc/ct_get_optblocker_u8/Makefile
  proofs/cbmc/ct_get_optblocker_u8/ct_get_optblocker_u8_harness.c
  proofs/cbmc/poly_permute_bitrev_to_custom/Makefile
  proofs/cbmc/poly_permute_bitrev_to_custom/poly_permute_bitrev_to_custom_harness.c
  proofs/cbmc/value_barrier_i32/Makefile
  proofs/cbmc/value_barrier_i32/value_barrier_i32_harness.c
  proofs/cbmc/value_barrier_u32/Makefile
  proofs/cbmc/value_barrier_u32/value_barrier_u32_harness.c
  proofs/cbmc/value_barrier_u8/Makefile
  proofs/cbmc/value_barrier_u8/value_barrier_u8_harness.c
  scripts/check-contracts
  scripts/lint
Labels: CBMC

#811 Keccak-F1600: Use d-form LDP/LDR instead of LD2
  dev/fips202/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
  mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
Labels: benchmark

#809 CI: Extend benchmark build-only tests
  .github/workflows/base.yml
  scripts/tests
Labels: benchmark

#819 CI: Run CBMC on c7g.4xlarge instead of c7g.2xlarge
  .github/workflows/cbmc.yml
Labels: CBMC
