Repository pq-code-package/mlkem-native, pull requests merged in 2025-06, with the labels that each got.

#1063 autogen: Extend autogeneration of #undef's to assembly files
  dev/aarch64_clean/src/rej_uniform_asm.S
  dev/aarch64_opt/src/rej_uniform_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x1_scalar_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x1_v84a_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x2_v84a_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
  dev/fips202/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm.S
  dev/fips202/aarch64_symbolic/keccak_f1600_x1_scalar_symbolic.S
  dev/fips202/aarch64_symbolic/keccak_f1600_x4_v8a_scalar_hybrid_clean.S
  dev/fips202/aarch64_symbolic/keccak_f1600_x4_v8a_v84a_scalar_hybrid_clean.S
  scripts/autogen
Labels: DO-NOT-MERGE

#1078 HOL-Light: Fix paths in Makefile
  proofs/hol_light/arm/Makefile
Labels: bug

#1080 ACVP: Adjust to additionally support ACVTS data format
  test/acvp_client.py
Labels: needs-mldsa-native-port

#1083 Nix: Remove zig 0.10 and zig 0.11 shells and CI
  .github/workflows/ci.yml
  flake.nix
Labels: needs-mldsa-native-port
